import Head from "next/head";
import CalendarHeatMap from "@/components/CalendarHeatMap";
import styles from "../styles/Home.module.css";
import Footer from "@/components/Footer";
import useSWR from "swr";
import fetcher from "@/lib/fetcher";

export default function Home() {
  const { data } = useSWR("/api/tweets", fetcher);
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <YoutubeViewsCount /> */}

      <CalendarHeatMap data={data} />

      <Footer />
    </div>
  );
}
