import Head from "next/head";
import Image from "next/image";
import YoutubeViewsCount from "../components/YoutubeViewsCount";
import TwitterData from "@/components/TwitterData";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <YoutubeViewsCount /> */}
      <TwitterData />

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Jesi
        </a>
      </footer>
    </div>
  );
}
